[build-system]
requires = ["setuptools>=68.2.2", "numpy>=1.22.0, <=1.26.4"]
build-backend = "setuptools.build_meta"

[project]
version = "0.0.7"
authors = [{name = "Andreas Mazur"}]
maintainers = [{name = "Andreas Mazur"}]
name = "geoconv"
description = "Intrinsic Surface Convolutions for everyone!"
license = {file = "LICENSE", text = """GeoConv provides implementations of- and interfaces to methods from publicly
available prior work for computing local coordinate systems on triangle mesh- or point cloud data and for performing
intrinsic surface convolutions, intended to facilitate academic purposes and non-commercial research on neural networks
operating on surface data. GeoConv is licensed under GNU General Public License v3.0, with the additional restriction
that it may solely be used for academic and non-commercial research purposes, unless prior written permission has been
granted by the owners of the methods utilized."""}
readme = "README.md"
keywords = [
    "surface",
    "surface-convolution",
    "convolution",
    "intrinsic-surface-convolution",
    "machine-learning",
    "deep-learning",
    "neural-network",
    "convolutional-neural-networks",
    "deep-neural-network",
    "tensorflow",
    "keras",
    "pytorch",
    "geometry",
    "geometry-processing",
    "geodesic",
    "geodesic-algorithm",
    "geometric",
    "geometric-deep-learning",
    "visualization",
    "benchmarking",
    "potpourri3d",
    "tqdm",
    "h5py"
]
requires-python = ">= 3.10"
dependencies = [
    "numpy>=1.22.0, <=1.26.4",
    "tqdm>=4.64.0",
    "trimesh>=3.12.6, <=4.4.7",
    "pyglet>=1.5.27",
    "matplotlib>=3.5.2",
    "open3d>=0.17.0",
    "networkx>=2.8.6",
    "pygeodesic>=0.1.7",
    "Pillow>=10.0.1",
    "scipy>=1.10.0",
    "pyglet<2",
    "pillow>=11.1.0"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[project.optional-dependencies]
pytorch = [
    "torch<=2.1.0",
    "torchvision<=0.16.0",
]
tensorflow = [
    "tensorflow",
    "tensorflow-probability",
    "tensorflow-datasets",
    "keras_tuner"
]
tensorflow_gpu = [
    "tensorflow[and-cuda]",
    "tensorflow-probability",
    "tensorflow-datasets"
]

[project.urls]
Repository = "https://github.com/andreasMazur/geoconv"
Issues = "https://github.com/andreasMazur/geoconv/issues"
